ChallengeWeather/ChallengeWeather/Models/ErrorViewModel.cs
using System;

namespace ChallengeWeather.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChallengeWeather/ChallengeWeather/Models/ZoneCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChallengeWeather.Models
{
    public class ZoneCard
    {
        public string Country { get; set; }
        public string City { get; set; }
    }
}

ChallengeWeather/ChallengeWeather/Components/ExtendedWeatherViewComponent.cs
using ChallengeWeather.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChallengeWeather.Components
{
    public class ExtendedWeatherViewComponent : ViewComponent
    {
        private readonly ICardService _zoneCardService;

        public ExtendedWeatherViewComponent(ICardService zoneCardService)
        {
            _zoneCardService = zoneCardService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            string cityToReturn = "Buenos Aires";

            if (TempData.ContainsKey("extendedData"))
                cityToReturn = TempData["extendedData"].ToString();

            var forecast = await _zoneCardService.GetCardsDataFromRepo(cityToReturn);

            return View(forecast);
        }
    }
}

ChallengeWeather/ChallengeWeather/Components/ReportCardViewComponent.cs
using ChallengeWeather.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ChallengeWeather.Components
{
    public class ReportCardViewComponent : ViewComponent
    {
        private readonly ICardService _zoneCardService;

        public ReportCardViewComponent(ICardService zoneCardService)
        {
            _zoneCardService = zoneCardService;
        }

        // Utilizará un TempData
        public async Task<IViewComponentResult> InvokeAsync(string searchedCity)
        {
            CultureInfo originalCulture = Thread.CurrentThread.CurrentCulture;
            Thread.CurrentThread.CurrentCulture = new CultureInfo("es-ES");


            string cityToReturn = "Buenos Aires";

            //TempData["searchedCity"]

            if (TempData.ContainsKey("searchedCity"))
                cityToReturn = TempData["searchedCity"].ToString(); 

            var forecast = await _zoneCardService.GetCardsDataFromRepo(cityToReturn);


            TempData["extendedData"] = cityToReturn;

            return View(forecast);
        }
    }
}

ChallengeWeather/ChallengeWeather/Components/ZoneCardViewComponent.cs
using ChallengeWeather.Core.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ChallengeWeather.Components
{
    public class ZoneCardViewComponent : ViewComponent
    {
        private readonly ICardService _zoneCardService;

        public ZoneCardViewComponent(ICardService zoneCardService)
        {
            _zoneCardService = zoneCardService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string searchedCity)
        {
            var cities = _zoneCardService.GetZoneCardsMockFromRepo();

            //if (searchedCity is not null)
            //{
            //    return View("ReportCard");
            //}

            return View(cities);
        }

        //[HttpPost]
        //public async Task<IViewComponentResult> test(string searchedCity)
        //{
        //    ViewData["City"] = searchedCity;

        //    return View();
        //}

        //POST Method con la ciudad (Recibirá una ciudad que debo guardar y enviar al ReportCardViewComponent).

    }
}

ChallengeWeather/ChallengeWeather/Controllers/HomeController.cs
using ChallengeWeather.Core.DTOs;
using ChallengeWeather.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ChallengeWeather.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

       
        [HttpPost]
        public IActionResult Search(IFormCollection formCollection)
        {
            var cityToReturn = formCollection["searchSelect"];

            TempData["searchedCity"] = cityToReturn.ToString();

            return RedirectToAction("Index");

            //return ViewComponent("ZoneCard", new { searchedCity = cityToReturn.ToString() });
        }
    }
}

ChallengeWeather/ChallengeWeather/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h3  style="font-weight:bold">SERVICIO DEL CLIMA</h3>
    <hr class="hrLineWellcome" style="border-color: coral !important">
</div>

ChallengeWeather/ChallengeWeather/Views/Shared/Components/ZoneCard/Default.cshtml
@model IEnumerable<ChallengeWeather.Core.DTOs.ZoneCardDTO>


<div class="card ReportZoneCards">
    <h3 style="color: #7278AD">Seleccioná la zona</h3>
    <hr class="inCardHrLine" style="border-color: #4661AF !important" />
    <br />
    <p class="tagPZone">Ciudad</p>
    @using (Html.BeginForm("Search", "Home", FormMethod.Post))
    {
        <select class="form-select searchSelect form-select-sm" id="searchSelect" name="searchSelect">
            <option>Seleccione una ciudad</option>
            @foreach (var item in Model)
            {

                <option value="@item.City">@Html.DisplayFor(modelItem => item.City)</option>

            }
        </select>
        <br />
        <div class="form-group">
            <input type="submit" class="btn btn-primary form-control btnSearchZoneCard" style="background-color: coral;" name="searchedCity" value="Buscar"/>
        </div>
    }

</div>

ChallengeWeather/ChallengeWeather/Views/Shared/_Layout.cshtml
@using System.Web.Mvc;
@using System.Web.Mvc.Html;
@using System.Web;
@{
    @ViewData["searchedCity"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChallengeWeather</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/custom.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-color: coral !important">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: white !important; font-weight: bold;">ChallengeWeather</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">

                        </li>
                        <li class="nav-item">

                        </li>
                    </ul>

                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link initSession" href="#">
                                Iniciar Sesión
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                                </svg>
                            </a>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            
            <div class="row">
                <div class="column">
                    @await Component.InvokeAsync("ZoneCard")
                </div>
                <div class="column">
                    @await Component.InvokeAsync("ReportCard")
                </div>
            </div>
            <div>
                @await Component.InvokeAsync("ExtendedWeather")
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color: black !important;">
        <div class="container">
            &copy; 2021 - ChallengeWeather - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>